routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CoursesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PublicController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [PublicController::class,'index']);
Route::get('/store', [PublicController::class,'store']);
Route::get('/product', [PublicController::class,'product']);
Route::get('/cart', [PublicController::class,'cart']);
Route::get('/checkout', [PublicController::class,'checkout']);
Route::get('/order', [PublicController::class,'orderComplete']);


Route::middleware(['auth'])->name('dashboard.')->group(function (){
    Route::get('admin/dashboard',[DashboardController::class,'home'])->name('home');

    Route::get('/dashboard/user', [DashboardController::class,'user'])->name('users');


    Route::get('/dashboard/products', [DashboardController::class,'products'])->name('products');
    Route::get('/dashboard/products/create', [DashboardController::class,'create'])->name('products.create');
    Route::post('/dashboard/products', [DashboardController::class,'store'])->name('products.store');

});

// Route::middleware(['auth'])->name('courses.')->group(function () {
//     Route::get('/courses', [CoursesController::class,'index'])->name('home');
//     Route::get('/courses/create', [CoursesController::class,'create'])->name('create');
//     Route::post('/courses', [CoursesController::class,'store'])->name('store');
//     Route::get('/courses/{course}/edit', [CoursesController::class, 'edit'])->name('edit');
//     Route::patch('/courses/{course}', [CoursesController::class, 'update'])->name('update');
//     Route::delete('/courses/{course}',[CoursesController::class,'destroy'])->name('delete');
// });

Route::middleware(['auth'])->resource('categories',CategoryController::class);

Route::get('/login',[AuthController::class,'login']);
Route::get('/registration',[AuthController::class,'registration']);


Route::get('/', function () {
    return view('welcome');
});



require __DIR__.'/auth.php';

resources/views/admin/categories.blade.php
<x-backend.layout.master>
    <x-slot:title>
        Categories page
    </x-slot:title>
    <x-slot:pageTitle>
        Categories
    </x-slot:pageTitle>
    <x-slot:pageIcon>
        mdi mdi-sitemap
    </x-slot:pageIcon>

    <a href="{{route('categories.create')}}" class="btn btn-primary mx-3">Create New</a>

    <h6 class="container card-title m-t-40"><i
        class="m-r-5 font-18 mdi mdi-format-list-numbers"></i> Products Category List</h6>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">title</th>
                <th scope="col">description</th>
                <th scope="col">Icon</th>
                <th scope="col">action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($categories as $category)
                <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{$category->title}}</td>
                    <td>{{$category->description}}</td>
                    <td>{{$category->Icon}}</td>
                    <td><a class="btn btn primary" href="#">Edit</a></td>
                    <td><a class="btn btn danger" href="#">Delete</a></td>
                </tr>
            @endforeach
            {{$categories->links()}}
        </tbody>
    </table>
</div>
</x-backend.layout.master>

resources/views/admin/courses.blade.php
<x-backend.layout.master>
    <x-slot:title>
        Courses page
    </x-slot:title>
    <x-slot:pageTitle>
        Courses
    </x-slot:pageTitle>
    <x-slot:pageIcon>
        mdi mdi-library-books
    </x-slot:pageIcon>

    <a href="{{route('courses.create')}}" class="btn btn-primary mx-3"><i class="mdi mdi-plus"></i> Create New</a>
    <a href="{{route('courses.create')}}" class="btn btn-secondary mx-3"> <i class="mdi mdi-delete-sweep"></i> Trash Can</a>

    @if ($errors->any())
    <x-backend.layout.alerts.errors />
    @endif

    <x-backend.layout.alerts.message type="success" :message="session('message')" class="mt-2" />

    <h6 class="container card-title m-t-40"><i
        class="m-r-5 font-18 mdi mdi-format-list-numbers"></i> Courses List</h6>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">title</th>
                <th scope="col">banner</th>
                <th scope="col">batch no</th>
                <th scope="col">course type</th>
                <th scope="col">instructor name</th>
                <th scope="col">Is Active</th>
                <th scope="col">class start date</th>
                <th scope="col">class end date</th>
                <th scope="col">action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($courses as $course)
                <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{$course->title}}</td>
                    <td><img
                        src="{{$course->banner ? asset('storage/'.$course->banner) : 'image empty'}}"
                        alt="course-banner" width="50px"
                    /></td>
                    <td>{{$course->batch_no}}</td>
                    <td>{{$course->course_type}}</td>
                    <td>{{$course->instructor_name}}</td>
                    <td>{{$course->is_active?'acive':'inactive'}}</td>
                    <td>{{$course->class_start_date}}</td>
                    <td>{{$course->class_end_date}}</td>
                    <td style="display: inline">

                        <a href="{{ route('courses.edit', ['course' => $course->id]) }}"><button type="button" class="btn btn-outline-primary"><i class="mdi mdi-grease-pencil"></i> Edit</button></a>

                        <form method="POST" action="{{ route('courses.delete', ['course' => $course->id]) }}">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-outline-danger"><i class="mdi mdi-delete"></i> Delete</button>
                        </form>

                    </td>



                </tr>
            @endforeach
        </tbody>
    </table>
</div>
</x-backend.layout.master>

resources/views/admin/create.blade.php
<x-backend.layout.master>

<x-slot:title>
    products create page
</x-slot:title>
<x-slot:pageTitle>
    Create New Product
</x-slot:pageTitle>
<x-slot:pageIcon>
    mdi mdi-library-plus
</x-slot:pageIcon>

<h5>Product caregory</h5>
<hr>
<form method="POST" action="{{route('dashboard.products.store')}}">
    @csrf
        <div class="form-group has-validation">
          <label for="title">Category Title</label>
          <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name ="title" placeholder="Enter Title">
          @error('title')
          <p class="form-text text-danger">
              {{$message}}
          </p>
          @enderror
        </div>

        <div class="form-group">
            <textarea name="description" class="form-control is_invalid" id="description" cols="20" rows="10"></textarea>
        @error('description')
            <p>
                {{$message}}
            </p>
        @enderror
        </div>
        <div class="form-check">
          <input type="checkbox" class="form-check-input" id="is_active" name="is_active" value="1" >
          <label class="form-check-label" for="is_active" >is active</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
</form>




</x-backend.layout.master>

resources/views/admin/create_course.blade.php
<x-backend.layout.master>

<x-slot:title>
    products create page
</x-slot:title>
<x-slot:pageTitle>
    Create New Product
</x-slot:pageTitle>
<x-slot:pageIcon>
    mdi mdi-library-plus
</x-slot:pageIcon>

@if ($errors->any())
<x-backend.layout.alerts.errors />
@endif

<h5>Product caregory</h5>
<hr>
<form class="container " method="POST" action="{{ route('courses.store') }}" enctype="multipart/form-data">
    @csrf
    <x-backend.layout.forms.label for="title" text="Title"/>     
    <x-backend.layout.forms.input name="title" type="text" :value="old('title')"/>

    <x-backend.layout.forms.label for="banner" text="Banner Image"/>     
    <x-backend.layout.forms.input name="banner" type="file" />

    <x-backend.layout.forms.label for="batch_no" text="Batch Number"/>     
    <x-backend.layout.forms.input name="batch_no" type="number" :value="old('batch_no')" />

    <x-backend.layout.forms.label for="course_type" text="Course Type"/>     
    <x-backend.layout.forms.input name="course_type" type="text" :value="old('course_type')"/>

    <x-backend.layout.forms.label for="instructor_name" text="Instructor Name"/>     
    <x-backend.layout.forms.input name="instructor_name" type="text" :value="old('instructor_name')"/>

    <x-backend.layout.forms.label for="class_start_date" text="Class Start Date"/>     
    <x-backend.layout.forms.input name="class_start_date" type="date" :value="old('class_start_date')"/>

    <x-backend.layout.forms.label for="class_end_date" text="Class End Date"/>     
    <x-backend.layout.forms.input name="class_end_date" type="date" :value="old('class_end_date')"/>
    
    <div class="form-check">
        <input name="is_active" class="form-check-input" type="checkbox" value="1" id="isActiveInput" checked>
        <label class="form-check-label" for="isActiveInput">
            Is Active
        </label>
    </div>

    <button class="btn btn-primary py-2 px-3"> Create</button>
</form>




</x-backend.layout.master>

resources/views/admin/edit_courses.blade.php
<x-backend.layout.master>

    <x-slot:title>
        products create page
    </x-slot:title>
    <x-slot:pageTitle>
        Create New Product
    </x-slot:pageTitle>
    <x-slot:pageIcon>
        mdi mdi-library-plus
    </x-slot:pageIcon>
    
    @if ($errors->any())
    <x-backend.layout.alerts.errors />
    @endif
    
    <h5>Product caregory</h5>
    <hr>
    <form class="container" method="POST" action="{{ route('courses.update',['course'=>$course->id]) }}" enctype="multipart/form-data">
        @csrf
        @method('PATCH')
        <x-backend.layout.forms.label for="title" text="Title"/>     
        <x-backend.layout.forms.input name="title" type="text" :value="old('title',$course->title)"/>
    
        <x-backend.layout.forms.label for="banner" text="Banner Image"/>     
        <x-backend.layout.forms.input name="banner" type="file" />
    
        <x-backend.layout.forms.label for="batch_no" text="Batch Number"/>     
        <x-backend.layout.forms.input name="batch_no" type="number" :value="old('batch_no',$course->batch_no)" />
    
        <x-backend.layout.forms.label for="course_type" text="Course Type"/>     
        <x-backend.layout.forms.input name="course_type" type="text" :value="old('course_type',$course->course_type)"/>
    
        <x-backend.layout.forms.label for="instructor_name" text="Instructor Name"/>     
        <x-backend.layout.forms.input name="instructor_name" type="text" :value="old('instructor_name',$course->instructor_name)"/>
    
        <x-backend.layout.forms.label for="class_start_date" text="Class Start Date"/>     
        <x-backend.layout.forms.input name="class_start_date" type="date" :value="old('class_start_date',$course->class_start_date)"/>
    
        <x-backend.layout.forms.label for="class_end_date" text="Class End Date"/>     
        <x-backend.layout.forms.input name="class_end_date" type="date" :value="old('class_end_date',$course->class_end_date)"/>
        
        <div class="form-check">
            <input name="is_active" class="form-check-input" type="checkbox" value="1" id="isActiveInput" checked>
            <label class="form-check-label" for="isActiveInput">
                Is Active
            </label>
        </div>
    
        <x-backend.layout.forms.button color="primary" class="mt-2" text="Create"/>
    </form>
    
    
    
    
    </x-backend.layout.master>

resources/views/admin/products.blade.php
<x-backend.layout.master>
    <x-slot:title>
        products page
    </x-slot:title>
    <x-slot:pageTitle>
        Products
    </x-slot:pageTitle>
    <x-slot:pageIcon>
        mdi mdi-airplay
    </x-slot:pageIcon>

    <a href="{{route('dashboard.products.create')}}" class="btn btn-primary mx-3">Create New</a>

    <h6 class="container card-title m-t-40"><i
        class="m-r-5 font-18 mdi mdi-format-list-numbers"></i> Products Category List</h6>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">title</th>
                <th scope="col">description</th>
                <th scope="col">is_active</th>
                <th scope="col">action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($categories as $category)
                <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{$category->title}}</td>
                    <td>{{$category->description}}</td>
                    <td>{{$category->is_active}}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
</x-backend.layout.master>

resources/views/admin/user.blade.php
<x-backend.layout.master>
    <x-slot:title>
        Users Page
    </x-slot:title>
    <x-slot:pageTitle>
        Users
    </x-slot:pageTitle>
    <x-slot:pageIcon>
        mdi mdi-account
    </x-slot:pageIcon>


    @if ($errors->any())
    <x-backend.layout.alerts.errors />
    @endif

    <x-backend.layout.alerts.message type="success" :message="session('message')" class="mt-2" />

    <h6 class="container card-title m-t-40"><i
        class="m-r-5 font-18 mdi mdi-format-list-numbers"></i> Users List</h6>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Role</th>
                <th scope="col">Action</th>

            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
            {{-- @dd($user->roles->name); --}}
                <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->roles->name}}</td>

                    <td style="display: inline">

                        <a href="#"><button type="button" class="btn btn-outline-primary"><i class="mdi mdi-grease-pencil"></i> Change Role</button></a>

                    </td>



                </tr>
            @endforeach
        </tbody>
    </table>
</div>
</x-backend.layout.master>